version: '2.1'

services: 

    bifurcation: 
        build: ./bifurcation
        ports:
            - 3000:3000

    web:
        build: ./ng-bifurcation
        ports: 
            - 80:80 
        depends_on: 
            - bifurcation 
